config/routes.rb
Rails.application.routes.draw do
  root 'pages#login'

  get '/dashboard', to: 'pages#dashboard'
  get '/expenses', to: 'pages#expenses'
  post '/login', to: 'pages#create', as: 'login_session'
  delete '/logout', to: 'pages#destroy', as: 'logout'

  resources :workers, except: [:show]
  resources :clients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  validates :name, presence: true
  validates :work_description, presence: true
  validates :initial_payment, presence: true, numericality: {:greater_than => 0}
  validates :total_pay, presence: true, numericality: {:greater_than => 0}
  validates :telephone, presence: true, format: { with: /\A\d{10}\z/, message: "Debe tener exactamente 10 dígitos" }
  validates :address, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_secure_password
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_one_attached :profile_picture
  validates :name, presence: true
  validates :position, presence: true
  validates :age, presence: true, numericality: {:greater_than => 0}
  validates :telephone, presence: true, format: { with: /\A\d{10}\z/, message: "Debe tener exactamente 10 dígitos" }
  validates :salary, presence: true, numericality: {:greater_than => 0}
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login, except: [:login, :create]

  private

  def require_login
    unless current_user
      flash[:error] = "Debes iniciar sesión para acceder a esta página"
      redirect_to root_path
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    @clients = Client.order(Arel.sql("CASE WHEN status = 'Finished' THEN 0 ELSE 1 END"))
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(worker_params)
    if @client.save
      flash[:success] = 'Cliente agregado con éxito'
      redirect_to clients_path
    else
      flash[:error] = 'Error al agregar cliente'
      render :new
    end
  end

  def update
    if @client.update(worker_params)
      flash[:info] = 'Cliente actualizado con éxito'
      redirect_to clients_path
    else
      flash[:error] = 'Error al actualizar cliente'
      render :edit
    end
  end

  def destroy
    if @client.destroy
      flash[:info] = 'Cliente eliminado con éxito'
    else
      flash[:error] = 'Error al eliminar cliente'
    end

    redirect_to clients_path
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def worker_params
    params.require(:client).permit(:name, :work_description, :status, :initial_payment, :total_pay, :telephone, :address, :start_date, :end_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def login
    redirect_to dashboard_path if current_user
  end

  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_path, flash: { info: 'Inicio de sesión exitoso.' }
    else
      redirect_to root_path, flash: { error: 'Error al ingresar el usuario o la contraseña.' }
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: { info: 'Sesión cerrada correctamente.' }
  end

  def dashboard
    @workers = Worker.count
    @clients_left = Client.where(status: "Process").count
    @clients_finished = Client.where(status: "Finished").count

  end

  def expenses
    @profits = Client.sum(:total_pay)
    @payments = Worker.sum(:salary)
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:edit, :update, :destroy]

  def index
    @workers = Worker.all
  end

  def new
    @worker = Worker.new
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      flash[:success] = 'Trabajador agregado con éxito'
      redirect_to workers_path
    else
      flash[:error] = 'Error al agregar trabajador'
      render :new
    end
  end

  def update
    if @worker.update(worker_params)
      flash[:info] = 'Trabajador actualizado con éxito'
      redirect_to workers_path
    else
      flash[:error] = 'Error al actualizar trabajador'
      render :edit
    end
  end

  def destroy
    if @worker.destroy
      flash[:info] = 'Trabajador eliminado con éxito'
    else
      flash[:error] = 'Error al eliminar trabajador'
    end

    redirect_to workers_path
  end

  private

  def set_worker
    @worker = Worker.find(params[:id])
  end

  def worker_params
    params.require(:worker).permit(:name, :position, :salary, :age, :address, :telephone, :profile_picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/clients/edit.html.erb
<%= render 'partials/menu' %>
<%= render 'form', title: 'Actualizar cliente', submit_button_text: 'Actualizar Cliente' %>

app/views/clients/index.html.erb
<%= render 'partials/menu' %>
<div class="p-4 sm:ml-64 dark:bg-gray-800 min-h-screen">
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
            <div class="flex justify-center items-center mb-20">
                <div class="flex flex-col text-center w-full">
                    <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900 dark:text-white">Clientes</h1>            
                </div>
                <div>
                    <%= link_to new_client_path, class: "flex justify-center items-center gap-2 w-28 h-12 cursor-pointer rounded-md shadow-2xl text-white font-semibold bg-gradient-to-r from-[#14b8a6] via-[#059669] to-[#047857] hover:shadow-xl hover:shadow-green-500 hover:scale-105 duration-300 hover:from-[#047857] hover:to-[#14b8a6]" do %>
                        <svg class="w-5 fill-white" viewBox="0 0 15 15">
                            <svg
                            class="w-6 h-6"
                            stroke="currentColor"
                            stroke-width="1.5"
                            viewBox="0 0 24 24"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                            >  
                                <path d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" stroke-linejoin="round" stroke-linecap="round"></path>
                            </svg>
                        </svg>
                    <% end %>
                </div>
            </div>
            <% if @clients.present? %>
                <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                            <tr>
                                <th scope="col" class="px-6 py-3">
                                    Nombre
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Status
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Teléfono
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Total a pagar
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Fecha a entregar
                                </th>
                                <th scope="col" class="px-6 py-3">
                                ‎     
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @clients.each do |client| %>
                                <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700 hover:bg-gray-100 dark:hover:bg-gray-700">
                                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                        <%= client.name %>
                                    </th>
                                   
                                    <td class="px-6 py-4">
                                        <% if client.status == "Process" %>
                                             <span class="inline-flex items-center bg-yellow-100 text-yellow-800 text-xs font-medium px-2.5 py-0.5 rounded-full dark:bg-yellow-900 dark:text-yellow-300">
                                                <span class="w-2 h-2 me-1 bg-yellow-500 rounded-full"></span>
                                                Proceso
                                            </span>
                                        <% else %>
                                            <span class="inline-flex items-center bg-green-100 text-green-800 text-xs font-medium px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300">
                                                <span class="w-2 h-2 me-1 bg-green-500 rounded-full"></span>
                                                Terminado
                                            </span>
                                        <% end %>
                                    </td>
                                    <td class="px-6 py-4">
                                        <%= client.telephone %>
                                    </td>
                                    <td class="px-6 py-4">
                                        $<%= client.total_pay %>
                                    </td>
                                    <td class="px-6 py-4">
                                        <%= client.end_date %>
                                    </td>
                              
                                    <td class="px-6 py-4">
                                        <div class="flex justify-center items-center"> 
                                            <a data-tooltip-target="delete-hover-<%= client.id %>" data-tooltip-trigger="hover">
                                                <%= button_to client_path(client), method: :delete, class: 'text-red-500 hover:text-red-700', onclick: "return confirm('¿Estás seguro de que deseas eliminar a este cliente?');" do %>
                                                    <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
                                                    </svg>
                                                <% end %>
                                            </a>
                                            <div id="delete-hover-<%= client.id %>" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-800">
                                                Eliminar cliente
                                                <div class="tooltip-arrow" data-popper-arrow></div>
                                            </div>
                                            
                                            <div class="flex justify-center items-center" data-tooltip-target="edit-hover-<%= client.id %>" data-tooltip-trigger="hover" type="button">
                                                <%= link_to edit_client_path(client), class: "ml-3 text-yellow-500 hover:text-yellow-700" do %>
                                                    <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m14.304 4.844 2.852 2.852M7 7H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-4.5m2.409-9.91a2.017 2.017 0 0 1 0 2.853l-6.844 6.844L8 14l.713-3.565 6.844-6.844a2.015 2.015 0 0 1 2.852 0Z"/>
                                                    </svg>
                                                <% end %>
                                            </div>
                                            <div id="edit-hover-<%= client.id %>" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-800">
                                                Actualizar cliente
                                                <div class="tooltip-arrow" data-popper-arrow></div>
                                            </div>

                                            <div class="flex justify-center items-center" data-tooltip-target="show-hover-<%= client.id %>" data-tooltip-trigger="hover" type="button">
                                                <%= link_to client_path(client), class: "ml-2  text-green-500 hover:text-green-700" do %>
                                                    <svg class="w-6 h-6" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                                                        <path stroke="currentColor" stroke-width="2" d="M21 12c0 1.2-4.03 6-9 6s-9-4.8-9-6c0-1.2 4.03-6 9-6s9 4.8 9 6Z"/>
                                                        <path stroke="currentColor" stroke-width="2" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                                                    </svg>
                                                <% end %>
                                            </div>
                                            <div id="show-hover-<%= client.id %>" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-800">
                                                Ver detalles
                                                <div class="tooltip-arrow" data-popper-arrow></div>
                                            </div>



                                             
                                        </div>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                       
                </div>
            <% else %>
                <p class="dark:text-gray-400">No hay clientes para mostrar.</p>
            <% end %>
        </div>
    </section>
</div>

app/views/clients/new.html.erb
<%= render 'partials/menu' %>
<%= render 'form', title: 'Agregar nuevo cliente', submit_button_text: 'Agregar Cliente' %>

app/views/clients/show.html.erb
<%= render 'partials/menu' %>
<div class="p-4 sm:ml-64 dark:bg-gray-800 min-h-screen">
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
            <div class="flex justify-center items-center mb-20">
                <div class="flex flex-col text-center w-full">
                    <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900 dark:text-white">Detalles del cliente</h1>            
                </div>
                <%= link_to edit_client_path, class: "flex justify-center items-center gap-2 w-28 h-12 cursor-pointer rounded-md shadow-2xl text-white font-semibold bg-gradient-to-r from-[#f4d03f] via-[#f4d03f] to-[#9a7d0a] hover:shadow-xl hover:shadow-yellow-500 hover:scale-105 duration-300 hover:from-[#9a7d0a] hover:to-[#f4d03f]" do %>
                    Actualizar
                <% end %>
            </div>
            <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-200 sm:flex-row flex-col">
                <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
                    <h2 class="text-gray-900 dark:text-white text-lg title-font font-medium mb-2">Datos de contacto</h2>
                    <p class="leading-relaxed text-base dark:text-gray-400">Nombre: <%= @client.name %></p>
                    <p class="leading-relaxed text-base dark:text-gray-400">Teléfono: <%= @client.telephone %></p>
                    <p class="leading-relaxed text-base dark:text-gray-400">Dirección: <%= @client.address %></p>
                </div>
            </div>
            <div class="flex items-center lg:w-3/5 mx-auto sm:flex-row flex-col">
                <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
                    <h2 class="text-gray-900 dark:text-white text-lg title-font font-medium mb-2">Detalles del trabajo</h2>
                    <p class="leading-relaxed text-base dark:text-gray-400">
                    Status: 
                        <% if @client.status == "Process" %>
                            <span class="inline-flex items-center bg-yellow-100 text-yellow-800 text-xs font-medium px-2.5 py-0.5 rounded-full dark:bg-yellow-900 dark:text-yellow-300">
                                <span class="w-2 h-2 me-1 bg-yellow-500 rounded-full"></span>
                                Proceso
                            </span>
                        <% else %>
                            <span class="inline-flex items-center bg-green-100 text-green-800 text-xs font-medium px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300">
                                <span class="w-2 h-2 me-1 bg-green-500 rounded-full"></span>
                                Terminado
                            </span>
                        <% end %>
                    </p>
                    <p class="leading-relaxed text-base dark:text-gray-400">Descripción del trabajo: <%= @client.work_description %></p>
                    <p class="leading-relaxed text-base dark:text-gray-400">Pago inicial: <%= @client.initial_payment %></p>
                    <p class="leading-relaxed text-base dark:text-gray-400">Total a pagar: <%= @client.total_pay %></p>
                    <p class="leading-relaxed text-base dark:text-gray-400">Fecha de inicio: <%= @client.start_date %></p>
                    <p class="leading-relaxed text-base dark:text-gray-400">Fecha a entregar: <%= @client.end_date %></p>
                </div>
                
            </div>
            <div class="flex items-center lg:w-3/5 mx-auto sm:flex-row flex-col mt-5">
                <div class="flex flex-col sm:flex-row sm:space-x-5 space-y-5 sm:space-y-0"> 
                    
                    <%= link_to "Regresar", clients_path, class: "p-5 flex justify-center items-center gap-2 h-12 cursor-pointer rounded-md shadow-2xl text-white font-semibold bg-gradient-to-r from-[#5dade2] via-[#2e86c1] to-[#21618c] hover:shadow-xl hover:shadow-blue-500 hover:scale-105 duration-300 hover:from-[#21618c] hover:to-[#5dade2]" %>
                </div>
            </div>
        </div>
    </section>
</div>

app/views/partials/_menu.html.erb
<nav class="fixed top-0 z-50 w-full bg-white border-b border-gray-200 dark:bg-gray-800 dark:border-gray-700">
  <div class="px-3 py-3 lg:px-5 lg:pl-3">
    <div class="flex items-center justify-between">
      <div class="flex items-center justify-start rtl:justify-end">
        <button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
            <span class="sr-only">Open sidebar</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
               <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
            </svg>
         </button>
        <div class="flex ms-2 md:me-24">
          <img src="https://flowbite.com/docs/images/logo.svg" class="h-8 me-3" alt="FlowBite Logo" />
          <span class="self-center text-xl font-semibold sm:text-2xl whitespace-nowrap dark:text-white">Rectificación de motores Castillo</span>
        </div>
      </div>
      <div class="flex items-center">
          <div class="flex items-center ms-3">
            <div>
              <%= render 'partials/theme' %>
              <%= render 'partials/notifications' %>
            </div>
          </div>
        </div>
    </div>
  </div>

</nav>
<aside id="logo-sidebar" class="fixed top-0 left-0 z-40 w-64 h-screen pt-20 transition-transform -translate-x-full bg-white border-r border-gray-200 sm:translate-x-0 dark:bg-gray-800 dark:border-gray-700" aria-label="Sidebar">
    <div class="flex flex-col justify-between h-full px-3 pb-4 bg-white dark:bg-gray-800">
        <div>
            <ul class="space-y-2 font-medium">
                <li>
                    <%= link_to dashboard_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-300 dark:hover:bg-gray-700 group #{'bg-gray-200 dark:bg-gray-700' if current_page?(dashboard_path)}" do %>                     
                        <svg class="w-6 h-6 flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                            <path fill-rule="evenodd" d="M4.857 3A1.857 1.857 0 0 0 3 4.857v4.286C3 10.169 3.831 11 4.857 11h4.286A1.857 1.857 0 0 0 11 9.143V4.857A1.857 1.857 0 0 0 9.143 3H4.857Zm10 0A1.857 1.857 0 0 0 13 4.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 21 9.143V4.857A1.857 1.857 0 0 0 19.143 3h-4.286Zm-10 10A1.857 1.857 0 0 0 3 14.857v4.286C3 20.169 3.831 21 4.857 21h4.286A1.857 1.857 0 0 0 11 19.143v-4.286A1.857 1.857 0 0 0 9.143 13H4.857Zm10 0A1.857 1.857 0 0 0 13 14.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 21 19.143v-4.286A1.857 1.857 0 0 0 19.143 13h-4.286Z" clip-rule="evenodd"/>
                        </svg>
                        <span class="ms-3">Dashboard</span>
                    <% end %>
                </li>
                 <li>
                    <%= link_to clients_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-300 dark:hover:bg-gray-700 group #{'bg-gray-200 dark:bg-gray-700' if current_page?(clients_path) || current_page?(new_client_path) || (params[:controller] == 'clients' && params[:action] == 'edit')}" do %>                     
                        <svg class="w-6 h-6 flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                            <path fill-rule="evenodd" d="M8 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 9a4 4 0 0 0-4 4v1a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-1a4 4 0 0 0-4-4H6Zm7.25-2.095c.478-.86.75-1.85.75-2.905a5.973 5.973 0 0 0-.75-2.906 4 4 0 1 1 0 5.811ZM15.466 20c.34-.588.535-1.271.535-2v-1a5.978 5.978 0 0 0-1.528-4H18a4 4 0 0 1 4 4v1a2 2 0 0 1-2 2h-4.535Z" clip-rule="evenodd"/>
                        </svg>
                        <span class="flex-1 ms-3 whitespace-nowrap">Clientes / Trabajos</span>
                    <% end %>
                </li>
                <li>
                    <%= link_to workers_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-300 dark:hover:bg-gray-700 group #{'bg-gray-200 dark:bg-gray-700' if current_page?(workers_path) || current_page?(new_worker_path) || (params[:controller] == 'workers' && params[:action] == 'edit')}" do %>                     
                        <svg class="w-6 h-6 flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                            <path fill-rule="evenodd" d="M12 6a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Zm-1.5 8a4 4 0 0 0-4 4 2 2 0 0 0 2 2h7a2 2 0 0 0 2-2 4 4 0 0 0-4-4h-3Zm6.82-3.096a5.51 5.51 0 0 0-2.797-6.293 3.5 3.5 0 1 1 2.796 6.292ZM19.5 18h.5a2 2 0 0 0 2-2 4 4 0 0 0-4-4h-1.1a5.503 5.503 0 0 1-.471.762A5.998 5.998 0 0 1 19.5 18ZM4 7.5a3.5 3.5 0 0 1 5.477-2.889 5.5 5.5 0 0 0-2.796 6.293A3.501 3.501 0 0 1 4 7.5ZM7.1 12H6a4 4 0 0 0-4 4 2 2 0 0 0 2 2h.5a5.998 5.998 0 0 1 3.071-5.238A5.505 5.505 0 0 1 7.1 12Z" clip-rule="evenodd"/>
                        </svg>
                        <span class="flex-1 ms-3 whitespace-nowrap">Personal</span>
                    <% end %>
                </li>
                 <li>
                    <%= link_to expenses_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-300 dark:hover:bg-gray-700 group #{'bg-gray-200 dark:bg-gray-700' if current_page?(expenses_path)}" do %>                     
                        <svg class="w-6 h-6 flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 17.345a4.76 4.76 0 0 0 2.558 1.618c2.274.589 4.512-.446 4.999-2.31.487-1.866-1.273-3.9-3.546-4.49-2.273-.59-4.034-2.623-3.547-4.488.486-1.865 2.724-2.899 4.998-2.31.982.236 1.87.793 2.538 1.592m-3.879 12.171V21m0-18v2.2"/>
                        </svg>
                        <span class="flex-1 ms-3 whitespace-nowrap">Gastos</span>
                    <% end %>
                </li>
            </ul>
        </div>
        <div>
            <ul class="pt-4 mt-4 space-y-2 font-medium border-t border-gray-200 dark:border-gray-700">
                <li>
                    <%= button_to logout_path, method: :delete, class: "flex items-center p-2 w-full text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" do %> 
                        <svg class="w-6 h-6 rotate-180 flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 12H8m12 0-4 4m4-4-4-4M9 4H7a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h2"/>
                        </svg>
                        <span class="flex-1 ms-3 whitespace-nowrap flex">Cerrar sesión</span>
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
</aside>

app/views/workers/edit.html.erb
<%= render 'partials/menu' %>
<%= render 'form', title: 'Actualizar trabajador', submit_button_text: 'Actualizar Trabajador' %>

app/views/workers/new.html.erb
<%= render 'partials/menu' %>
<%= render 'form', title: 'Agregar nuevo trabajador', submit_button_text: 'Agregar Trabajador' %>